### ISSUE TITLE
Interactive Interface

### ISSUE THREAD

**Issue by Abhiroop25902** [dsc-iiest/todo-cli#2]
Create a command line interface for the following:
- [ ] Insert a todo with deadline, if any
- [ ] Write in terminal if any todo's deadline is passed in meaningful way (currently it's in very rudimentary form)
- [ ] make an interface to "gracefully" exit the script (something like `exit()` command to close the script, rather than to do `Ctrl + C`)

**Comment by LustigePerson** [comment]
I would like to take care of this.

Is the second point about printing to all running terminals, or only for a given user? Or only in the instance were the tool running?

**Comment by raushnn** [comment]
I would like to take this issue.

**Comment by arnabsen1729** [comment]
@IanFindlay your approach LGTM, but will take a look at depth once you make the PR. And since you messaged first the issue should be assigned to you. If we see no progress then we might assign the issue to @raushnn.

Just a suggestion:
- if you want to start working on an issue, first let the maintainers know and assign the issue to you.
- If you want to show your progress you can create a PR and then mark it WIP (Work In Progress). Read the docs [here](https://github.blog/2019-02-14-introducing-draft-pull-requests/). It is much easier to see the changes you have made that way than sharing the entire forked repo.

**Comment by Abhiroop25902** [comment]
@IanFindlay saw your changes, it's going great
some additions that will be helpful
- give some hints about what are the possible command (I know you have added exit, but also "add" and in future "view")
- add another option "help" which will list all the possible commands available

Also another thing, don't keep the thread creation and execution part in the infinity loop. With time, many threads with same task will be formed, wasting resources

**Comment by Abhiroop25902** [comment]
Issue fixed by #17, closing the issue
